import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Wrapper from "@/components/layout/Wrapper";
import Navbar from "@/components/layout/Navbar";
import useAuthGuard from "@/lib/hooks/useAuth";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="bg-gray-900 text-white min-h-screen flex flex-col">    
        <main className="flex-1 flex items-center justify-center">
          <Wrapper>{children}</Wrapper>
        </main>
      </body>
    </html>
  );
}
